services:
  - type: web
    name: fastapi-wood-classifier
    env: python
    plan: free
    buildCommand: ""
    startCommand: ./start.sh
    autoDeploy: true
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
